version: "2"

services:
  elasticsearch:
    image: elasticsearch:7.13.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - //c/es-data:/usr/src/app/
  
  kibana:
    image: kibana:7.13.3
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"